import os

"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ["PrimaryUI.py", "config_processing.py", "GenerateReport.py", "BackEnd.py"]
OPTIONS = {'argv_emulation': True}
files = os.listdir(os.getcwd() + "/config_files")
for x in files:
    DATA_FILES.append("/config_files" + x)
setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
